#! /usr/bin/env bash

DN_NAME=$(basename ${PWD})
CONTAINER_NAME="docknet-${DN_NAME}"

mkdir -p ~/.local/share/NuGet
mkdir -p ~/.nuget

# Mount PWD to container as basename of path,
# and mount host's NuGet directories
docker run --rm -v="${PWD}:/${DN_NAME}" \
    -v "${HOME}/.local/share/NuGet:/root/.local/share/NuGet" \
    -v "${HOME}/.nuget:/root/.nuget" \
    -w="/${DN_NAME}"  rendlelabs/docknet $@
